language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t tienduynguyen/simple-docker-react -f Dockerfile.dev .
  # docker build -t <username docker>/<name  image> -f <Dockerfile>

script:
  - docker run -e CI=true -it tienduynguyen/simple-docker-react yarn test --coverage

branches:
  only:
    - master
